trigger:
  branches:
    include:
      - main

variables:
  imageName: 'fastapiproject'
  tag: 'latest'
  azureSubscription: 'Azure subscription 1'
  acrName: 'fastapiproject'
  acrLoginServer: 'fastapiproject.azurecr.io'
  appServiceName: 'fastapiprojectweb'
  resourceGroup: 'fastapi-rg'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-ServiceConnection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployApp
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appServiceName)'
              containers: '$(acrLoginServer)/$(imageName):$(tag)'
