"""add autoincreent to tables

Revision ID: eeafec1868d5
Revises: cadd6a6b4a57
Create Date: 2025-06-08 21:57:56.207308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeafec1868d5'
down_revision: Union[str, None] = 'cadd6a6b4a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
